// Generated by scripts/generate-chromosome-data.mjs -- do not edit by hand.
//
// Sources:
//   metadata/ideogram_9606_GCF_000001305.16_850_V1.txt
//     NCBI Genome Decoration Page ideogram table, GRCh38, 850-band resolution.
//     Supplies the cytogenetic banding drawn into the SVGs and the base-pair
//     length of each chromosome (the largest bp_stop on that chromosome).
//   metadata/merge_hrc_topmed_stats.json
//     Per-chromosome TopMed and HRC entry counts.
//
// Regenerate with: npm run generate:chromosome-data

export type ChromosomeStat = {
  /** Chromosome name, "1" through "22" and "X". */
  chromosome: string;
  /** Length in base pairs on GRCh38. */
  basePairs: number;
  /** Variant rows in TopMed (hg38). */
  topmedEntries: number;
  /** Variant rows in the HRC hg19 release. */
  hg19Entries: number;
  /** HRC rows that carry Mapped_in_HRC = Y in TopMed. */
  mappedInHrc: number;
  /** hg19Entries as a percentage of topmedEntries, as reported upstream. */
  hrcVsTopmedPct: number;
  /** Site-absolute path to the generated ideogram SVG. */
  ideogram: string;
};

export const chromosomeStats: ChromosomeStat[] = [
  { chromosome: '1', basePairs: 248956422, topmedEntries: 57577226, hg19Entries: 3069931, mappedInHrc: 2992535, hrcVsTopmedPct: 5.3318, ideogram: '/assets/images/chromosomes/chr1.svg' },
  { chromosome: '2', basePairs: 242193529, topmedEntries: 61727855, hg19Entries: 3392237, mappedInHrc: 3320470, hrcVsTopmedPct: 5.4955, ideogram: '/assets/images/chromosomes/chr2.svg' },
  { chromosome: '3', basePairs: 198295559, topmedEntries: 50368782, hg19Entries: 2821894, mappedInHrc: 2764965, hrcVsTopmedPct: 5.6025, ideogram: '/assets/images/chromosomes/chr3.svg' },
  { chromosome: '4', basePairs: 190214555, topmedEntries: 48490718, hg19Entries: 2787581, mappedInHrc: 2731367, hrcVsTopmedPct: 5.7487, ideogram: '/assets/images/chromosomes/chr4.svg' },
  { chromosome: '5', basePairs: 181538259, topmedEntries: 45439747, hg19Entries: 2588168, mappedInHrc: 2536624, hrcVsTopmedPct: 5.6958, ideogram: '/assets/images/chromosomes/chr5.svg' },
  { chromosome: '6', basePairs: 170805979, topmedEntries: 42027327, hg19Entries: 2460111, mappedInHrc: 2405182, hrcVsTopmedPct: 5.8536, ideogram: '/assets/images/chromosomes/chr6.svg' },
  { chromosome: '7', basePairs: 159345973, topmedEntries: 40659953, hg19Entries: 2289305, mappedInHrc: 2235309, hrcVsTopmedPct: 5.6304, ideogram: '/assets/images/chromosomes/chr7.svg' },
  { chromosome: '8', basePairs: 145138636, topmedEntries: 39139389, hg19Entries: 2242705, mappedInHrc: 2195324, hrcVsTopmedPct: 5.73, ideogram: '/assets/images/chromosomes/chr8.svg' },
  { chromosome: '9', basePairs: 138394717, topmedEntries: 32559922, hg19Entries: 1686471, mappedInHrc: 1646301, hrcVsTopmedPct: 5.1796, ideogram: '/assets/images/chromosomes/chr9.svg' },
  { chromosome: '10', basePairs: 133797422, topmedEntries: 34039169, hg19Entries: 1927503, mappedInHrc: 1876436, hrcVsTopmedPct: 5.6626, ideogram: '/assets/images/chromosomes/chr10.svg' },
  { chromosome: '11', basePairs: 135086622, topmedEntries: 35116087, hg19Entries: 1936990, mappedInHrc: 1888356, hrcVsTopmedPct: 5.516, ideogram: '/assets/images/chromosomes/chr11.svg' },
  { chromosome: '12', basePairs: 133275309, topmedEntries: 33594199, hg19Entries: 1848117, mappedInHrc: 1812160, hrcVsTopmedPct: 5.5013, ideogram: '/assets/images/chromosomes/chr12.svg' },
  { chromosome: '13', basePairs: 114364328, topmedEntries: 25226068, hg19Entries: 1385433, mappedInHrc: 1359178, hrcVsTopmedPct: 5.4921, ideogram: '/assets/images/chromosomes/chr13.svg' },
  { chromosome: '14', basePairs: 107043718, topmedEntries: 22267236, hg19Entries: 1270436, mappedInHrc: 1242797, hrcVsTopmedPct: 5.7054, ideogram: '/assets/images/chromosomes/chr14.svg' },
  { chromosome: '15', basePairs: 101991189, topmedEntries: 20974445, hg19Entries: 1139215, mappedInHrc: 1109442, hrcVsTopmedPct: 5.4314, ideogram: '/assets/images/chromosomes/chr15.svg' },
  { chromosome: '16', basePairs: 90338345, topmedEntries: 23665360, hg19Entries: 1281297, mappedInHrc: 1251867, hrcVsTopmedPct: 5.4142, ideogram: '/assets/images/chromosomes/chr16.svg' },
  { chromosome: '17', basePairs: 83257441, topmedEntries: 20260822, hg19Entries: 1090072, mappedInHrc: 1068295, hrcVsTopmedPct: 5.3802, ideogram: '/assets/images/chromosomes/chr17.svg' },
  { chromosome: '18', basePairs: 80373285, topmedEntries: 20199166, hg19Entries: 1104755, mappedInHrc: 1083368, hrcVsTopmedPct: 5.4693, ideogram: '/assets/images/chromosomes/chr18.svg' },
  { chromosome: '19', basePairs: 58617616, topmedEntries: 15126485, hg19Entries: 868554, mappedInHrc: 851073, hrcVsTopmedPct: 5.7419, ideogram: '/assets/images/chromosomes/chr19.svg' },
  { chromosome: '20', basePairs: 64444167, topmedEntries: 16274345, hg19Entries: 884983, mappedInHrc: 868341, hrcVsTopmedPct: 5.4379, ideogram: '/assets/images/chromosomes/chr20.svg' },
  { chromosome: '21', basePairs: 46709983, topmedEntries: 9663610, hg19Entries: 531276, mappedInHrc: 513077, hrcVsTopmedPct: 5.4977, ideogram: '/assets/images/chromosomes/chr21.svg' },
  { chromosome: '22', basePairs: 50818468, topmedEntries: 10117751, hg19Entries: 524544, mappedInHrc: 510771, hrcVsTopmedPct: 5.1844, ideogram: '/assets/images/chromosomes/chr22.svg' },
  { chromosome: 'X', basePairs: 156040895, topmedEntries: 29114100, hg19Entries: 1273927, mappedInHrc: 1259283, hrcVsTopmedPct: 4.3756, ideogram: '/assets/images/chromosomes/chrX.svg' }
];
